### ISSUE TITLE
Typo in Silver Topaz Necklace?

### ISSUE THREAD

**Issue by Jordy3D** [mythridium/item-descriptions-expanded#1]
Not in a position to make a PR to update it right now, so I thought I'd just mention it here.
I believe this
![image](https://github.com/mythridium/item-descriptions-expanded/assets/19144524/9e066365-6a4e-4a49-8616-f669211a8eed)
is meant to read
```
The pairing of topaz and silver in this necklace sharpens your senses and lightens your blade.
```
?
If the other language variants were copied from that, this issue may extend to them as well (unless GPT understood the typo and fixed it)

**Comment by mythridium** [comment]
Thanks for reporting this, thankfully gpt was smart enough to translate these correctly from the few languages I checked, so only needed to clean this up in English.

Fixed in 096a566ac1b481244c13ff6389a9d810fa53cbac
